import React, { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

interface Timbre {
  id: number;
  nombre: string;
  usuario: string;
}

export default function Dashboard() {
  const [timbres, setTimbres] = useState<Timbre[]>([]);
  const [nombre, setNombre] = useState("");
  const [usuario, setUsuario] = useState("");
  const [editando, setEditando] = useState<number | null>(null);

  const handleAgregar = () => {
    if (!nombre || !usuario) return;
    setTimbres([
      ...timbres,
      { id: Date.now(), nombre, usuario }
    ]);
    setNombre("");
    setUsuario("");
  };

  const handleEditar = (timbre: Timbre) => {
    setEditando(timbre.id);
    setNombre(timbre.nombre);
    setUsuario(timbre.usuario);
  };

  const handleGuardar = () => {
    if (!nombre || !usuario || editando === null) return;
    setTimbres(
      timbres.map(t =>
        t.id === editando ? { ...t, nombre, usuario } : t
      )
    );
    setEditando(null);
    setNombre("");
    setUsuario("");
  };

  const handleBorrar = (id: number) => {
    setTimbres(timbres.filter(t => t.id !== id));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <ol>
            <li>
              Get started by editing <code>pages/index.tsx</code>.
            </li>
            <li>Save and see your changes instantly.</li>
          </ol>

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="/vercel.svg"
                alt="Vercel logomark"
                width={20}
                height={20}
              />
              Deploy now
            </a>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              Read our docs
            </a>
          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            Learn
          </a>
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Examples
          </a>
          <a
            href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go to nextjs.org →
          </a>
        </footer>
      </div>
      <div style={{ maxWidth: 600, margin: "40px auto", fontFamily: "sans-serif" }}>
        <h1>Panel de Administración QRing Pro</h1>
        <h2>Timbres</h2>
        <ul>
          {timbres.map((t) => (
            <li key={t.id} style={{ marginBottom: 10 }}>
              <b>{t.nombre}</b> - Usuario: {t.usuario}
              <button onClick={() => handleEditar(t)} style={{ marginLeft: 10 }}>Editar</button>
              <button onClick={() => handleBorrar(t.id)} style={{ marginLeft: 5, color: "red" }}>Borrar</button>
            </li>
          ))}
        </ul>
        <input
          type="text"
          placeholder="Nombre del timbre"
          value={nombre}
          onChange={e => setNombre(e.target.value)}
          style={{ marginRight: 10 }}
        />
        <input
          type="text"
          placeholder="Usuario asignado"
          value={usuario}
          onChange={e => setUsuario(e.target.value)}
          style={{ marginRight: 10 }}
        />
        {editando ? (
          <button onClick={handleGuardar}>Guardar cambios</button>
        ) : (
          <button onClick={handleAgregar}>Agregar timbre</button>
        )}
      </div>
    </>
  );
}
